# Generated by Django 6.0.6 on 2026-06-22 21:33

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='A short summary shown on the About page')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('opening_time', models.TimeField(help_text='Daily opening time, for example 12:00')),
                ('closing_time', models.TimeField(help_text='Daily closing time, for example 22:00')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(help_text='Unique number identifying this table on the floor plan', unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests this table can seat')),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('private', 'Private Dining Room'), ('bar', 'Bar Area')], default='indoor', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to temporarily remove this table from the booking flow')),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('12:00', '12:00 PM  —  Lunch'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('18:00', '6:00 PM  —  Dinner'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM  —  Last Seating')], max_length=5)),
                ('guest_count', models.PositiveIntegerField(help_text='Total number of guests including the person booking')),
                ('special_requests', models.TextField(blank=True, default='', help_text='Dietary requirements, celebrations, or any other notes for the kitchen')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.table')),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'constraints': [models.UniqueConstraint(fields=('table', 'date', 'time_slot'), name='unique_table_date_timeslot')],
            },
        ),
    ]
